kind: Secret
apiVersion: v1
metadata:
  name: anythingllm-api
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/description: API key for AnythingLLM automation
    openshift.io/display-name: AnythingLLM API Key
data:
  key: c2stYXV0b21hdGlvbi13b3Jrc3BhY2Utc2V0dXA=
type: Opaque
