---
#Ref: https://github.com/Mintplex-Labs/anything-llm/blob/master/docker/.env.example
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.model.name }}-vllm-cpu
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    opendatahub.io/connection-type-ref: anythingllm-generic-openai
    openshift.io/description: Connect to a {{ .Values.model.name }} model
    openshift.io/display-name: vLLM CPU {{ .Values.model.name }}
data:
  DISABLE_TELEMETRY: dHJ1ZQ==
  EMBEDDING_ENGINE: bmF0aXZl
  LLM_PROVIDER: Z2VuZXJpYy1vcGVuYWk=
  GENERIC_OPEN_AI_API_KEY: c2stZHVtbXk=
  GENERIC_OPEN_AI_BASE_PATH: aHR0cDovL29wdC0xMjVtLWNwdS1wcmVkaWN0b3I6ODA4MC92MQ==
  GENERIC_OPEN_AI_MODEL_PREF: b3B0LTEyNW0=
  GENERIC_OPEN_AI_MODEL_TOKEN_LIMIT: NTEy
  VECTOR_DB: bGFuY2VkYg==
type: Opaque