{{- if and .Values.signing.enabled .Values.signing.publicKey }}
apiVersion: v1
kind: Secret
metadata:
  name: cosign-pubkey
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  cosign.pub: {{ .Values.signing.publicKey }}
{{- end }}
