---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: {{ .Values.model.name }}-cpu
    serving.kserve.io/deploymentMode: RawDeployment
  name: {{ .Values.model.name }}-cpu
  labels:
    opendatahub.io/dashboard: 'true'
    networking.knative.dev/visibility: cluster-local
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: {{ .Values.resources.inference.limits.cpu | quote }}
          memory: {{ .Values.resources.inference.limits.memory | quote }}
        requests:
          cpu: {{ .Values.resources.inference.requests.cpu | quote }}
          memory: {{ .Values.resources.inference.requests.memory | quote }}
      runtime: vllm-cpu
