{{- if .Values.signing.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-10"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.signing.storageSize | default "5Gi" }}
  storageClassName: {{ .Values.storageClassName }}
{{- end }}
