{{- if and .Values.signing.enabled .Values.signing.publicKeyData }}
apiVersion: v1
kind: Secret
metadata:
  name: model-signing-pubkey
type: Opaque
data:
  signing-key.pub: {{ .Values.signing.publicKeyData | b64enc }}
{{- end }}
